# Generated by Django 2.0.1 on 2019-10-11 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product_field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_name', models.CharField(max_length=25)),
                ('Product_description', models.CharField(max_length=25)),
                ('Product_cost', models.CharField(max_length=25)),
                ('no_of_products', models.CharField(max_length=25)),
            ],
        ),
    ]
