# Generated by Django 2.0.1 on 2019-10-12 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_user_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buyed_product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_name', models.CharField(max_length=25)),
                ('user_email', models.CharField(max_length=25)),
                ('cost_product', models.CharField(max_length=25)),
            ],
        ),
    ]
