# Generated by Django 2.0.1 on 2019-10-19 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_buyed_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_field',
            name='Product_cost',
            field=models.IntegerField(max_length=25),
        ),
        migrations.AlterField(
            model_name='user_field',
            name='Account_balance',
            field=models.IntegerField(max_length=25),
        ),
    ]
