# Generated by Django 2.0.1 on 2019-10-21 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_buyed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_field',
            name='Product_cost',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='user_field',
            name='Account_balance',
            field=models.IntegerField(),
        ),
    ]
